<?php


return array (
	'CLASSES_DIR' 				=>	SJB_BASE_DIR.'system/core/',
	'MODULES_DIR'				=>	SJB_BASE_DIR.'system/modules/',
	'TEMPLATES_DIR'				=>	'templates/',
	'SYSTEM_TEMPLATE_DIR'		=>	'_system',
	'COMPILED_TEMPLATES_DIR'	=>	SJB_BASE_DIR.'system/cache/smarty/',
	'SMARTY_PATH'				=>	SJB_BASE_DIR.'system/ext/Smarty/Smarty.class.php',
	'LIBRARY_DIR'				=>	SJB_BASE_DIR.'system/lib/',
	'EXT_LIBRARY_DIR'			=>	SJB_BASE_DIR.'system/ext/',
	'SYSTEM_ACCESS_TYPE'		=>	'admin',
	'STARTUP_MODULE'			=>	'main',
	'STARTUP_FUNCTION'			=>	'show_admin_page',
	'SYSTEM_URL_BASE'			=>	'system',
	'SYSTEM_DEFAULT_TEMPLATE'	=>	'index.tpl',
	'LOCALE'					=>	'en-us',
	//'ROOT_DIR'					=>	'/admin/',
	'ADMIN_ACCESS_TYPE'			=>	'admin',
	'PAGE_TEMPLATES_MODULE_NAME'=>	'main',
	'DEFAULT_THEME'				=>	'_system/admin',
	'SCRIPTS_DIR'				=>	SJB_BASE_DIR.'system/admin-scripts/',
	'EXTERNAL_COMPONENTS_DIR'	=>	'../system/ext/',
	'FILES_DIR'					=>	SJB_BASE_DIR.'files/',
	'VIDEO_FILES_DIR'			=>	'videos/',
	'UPLOAD_FILES_DIRECTORY'	=> '../files',
	'EXPORT_FILES_DIRECTORY'	=> '../temp/export',
	'TEMP_FILES_DIRECTORY'		=> '../temp',
	'USER_CONFIG_FILE'			=> '../config.php',
	'LanguageIDMaxLength'		=> 256,
	'LanguageCaptionMaxLength'	=> 256,
	'DateFormatValidSymbols'	=> 'yYmd',
	'DateFormatMaxLength'		=> 50,
	'ValidThousandsSeparators'	=> ' ,.',
	'ValidDecimalsSeparators'	=> ',.',
	'PhraseIDMaxLength'			=> 1000,
	'TranslationMaxLength'		=> 2000,
	'I18NSettings_PathToLanguageFiles' => '../languages',
	'I18NSettings_FileNameTemplateForLanguageFile' => '%s.xml',
	'ADMIN_SPLASH_SCREEN_URL'	=> 'splash.htm',
	'SJB_VERSION'	=> '3.3',
	'PLUGINS_DIR'				=> '../system/plugins',
);

